Loading gpytorch/gpu-cuda-11.6/pytorch-1.11.0/1.8.0
  Loading requirement: cudnn/8.4.1 pytorch/gpu-cuda-11.6/1.11.0
Traceback (most recent call last):
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1D.py", line 340, in <module>
    gp_pipeline = GPModelPipeline(csv_file='M_2_fixed.csv', output_dir=output_dir)
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1D.py", line 201, in __init__
    self.initialize_model()
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1D.py", line 229, in initialize_model
    self.model = MultitaskGP(self.x_train, self.y_train, self.x_valid, self.y_valid, self.likelihood)
  File "/raven/u/dvoss/al_pmssmwithgp/model/multitaskGP.py", line 163, in __init__
    self.load_state_dict(state_dict)
  File "/mpcdf/soft/SLE_15/packages/skylake/pytorch/gpu-cuda-11.6/anaconda_3_2021.11-2021.11/1.11.0/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1497, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MultitaskGP:
	size mismatch for covar_module.raw_lengthscale: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([1, 1]).
srun: error: ravg1167: task 0: Exited with exit code 1
srun: Terminating StepId=12130112.0
