Loading gpytorch/gpu-cuda-11.6/pytorch-1.11.0/1.8.0
  Loading requirement: cudnn/8.4.1 pytorch/gpu-cuda-11.6/1.11.0
Traceback (most recent call last):
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1Dtest.py", line 233, in <module>
    gp_pipeline.train_model(iters=1000)
  File "/raven/u/dvoss/al_pmssmwithgp/model/GPmodel1Dtest.py", line 67, in train_model
    self.best_model, self.losses, self.losses_valid = self.model.do_train_loop(iters=iters)
  File "/raven/u/dvoss/al_pmssmwithgp/model/multitaskGP.py", line 106, in do_train_loop
    output = self(self.x_train)
  File "/mpcdf/soft/SLE_15/packages/skylake/gpytorch/gpu-cuda-11.6/pytorch-1.11.0/anaconda_3_2021.11-2021.11/1.8.0/lib/python3.9/site-packages/gpytorch/models/exact_gp.py", line 245, in __call__
    inputs = [i.unsqueeze(-1) if i.ndimension() == 1 else i for i in args]
  File "/mpcdf/soft/SLE_15/packages/skylake/gpytorch/gpu-cuda-11.6/pytorch-1.11.0/anaconda_3_2021.11-2021.11/1.8.0/lib/python3.9/site-packages/gpytorch/models/exact_gp.py", line 245, in <listcomp>
    inputs = [i.unsqueeze(-1) if i.ndimension() == 1 else i for i in args]
AttributeError: 'tuple' object has no attribute 'ndimension'
srun: error: ravg1132: task 0: Exited with exit code 1
srun: Terminating StepId=12180750.0
